import { db, now, uid } from "../../db";
import { compressImage } from "../../media";
import type { AssociationCard, AssociationCategory, MediaAsset } from "../../types";
import type { TabProps } from "../SongEditor";
import { BlobImage } from "../ui";

const categories: AssociationCategory[] = ["次の歌詞", "物語", "人物", "感情", "MV映像", "色", "音", "小道具", "自由メモ"];

export function AssociationsTab({ song, workspace, setWorkspace, queueSave, notify }: TabProps) {
  async function addCard() { const card: AssociationCard = { id: uid(), songId: song.id, category: "自由メモ", text: "", color: "#d8c6cf", createdAt: now(), updatedAt: now() }; await db.associations.add(card); setWorkspace((data) => ({ ...data, associations: [card, ...data.associations] })); }
  function patchCard(card: AssociationCard, patch: Partial<AssociationCard>) { const updated = { ...card, ...patch, updatedAt: now() }; setWorkspace((data) => ({ ...data, associations: data.associations.map((x) => x.id === card.id ? updated : x) })); queueSave(db.associations, updated); }
  async function removeCard(card: AssociationCard) { if (!window.confirm("この連想カードを削除しますか？")) return; await db.associations.delete(card.id); setWorkspace((data) => ({ ...data, associations: data.associations.filter((x) => x.id !== card.id) })); }
  async function addImage(card: AssociationCard, file?: File) { if (!file) return; try { const blob = await compressImage(file); const asset: MediaAsset = { id: uid(), songId: song.id, kind: "image", name: file.name, mimeType: blob.type, blob, size: blob.size, links: [{ type: "association", id: card.id }], createdAt: now(), updatedAt: now() }; await db.media.add(asset); await db.associations.update(card.id, { imageAssetId: asset.id, updatedAt: now() }); setWorkspace((data) => ({ ...data, media: [...data.media, asset], associations: data.associations.map((x) => x.id === card.id ? { ...x, imageAssetId: asset.id } : x) })); } catch (error) { notify(error instanceof Error ? error.message : "画像を保存できませんでした。"); } }
  const lyricOptions = workspace.lines.filter((line) => line.text.trim());
  return <section className="tab-page"><div className="tab-heading"><h2>連想</h2><button className="primary compact" onClick={addCard}>＋ カード</button></div><p className="tab-intro">歌詞を編集しても、歌詞行との関連付けは維持されます。</p>
    <div className="association-grid">{workspace.associations.map((card) => { const image = workspace.media.find((asset) => asset.id === card.imageAssetId); const linked = workspace.lines.find((line) => line.id === card.relatedLyricId); return <article className="association-card" key={card.id} style={{ "--card-color": card.color } as React.CSSProperties}><div className="card-color-line" /><div className="association-fields"><div className="association-top"><select value={card.category} onChange={(e) => patchCard(card, { category: e.target.value as AssociationCategory })}>{categories.map((x) => <option key={x}>{x}</option>)}</select><input type="color" aria-label="カード色" value={card.color} onChange={(e) => patchCard(card, { color: e.target.value })} /><button className="danger-text" onClick={() => removeCard(card)}>削除</button></div><label className="source-line"><span>関連する歌詞</span><select value={card.relatedLyricId ?? ""} onChange={(e) => patchCard(card, { relatedLyricId: e.target.value || undefined })}><option value="">未選択</option>{lyricOptions.map((line) => <option key={line.id} value={line.id}>{line.text}</option>)}</select></label>{linked && <blockquote>〽 {linked.text}</blockquote>}<textarea value={card.text} onChange={(e) => patchCard(card, { text: e.target.value })} placeholder="内容を入力" />{image && <div className="association-image"><BlobImage blob={image.blob} alt={image.name} /></div>}<label className="small-file"><input type="file" accept="image/*" onChange={(e) => addImage(card, e.target.files?.[0])} />{image ? "画像を変更" : "＋ 画像を追加"}</label></div></article>; })}</div>
    {!workspace.associations.length && <div className="empty-card"><h3>連想カードがありません</h3><p>歌詞に関連するメモをカードとして保存できます。</p><button className="primary" onClick={addCard}>カードを作成</button></div>}
  </section>;
}
