import { useEffect, useState } from "react";
import { createBackupBlob } from "../../backup";
import { db } from "../../db";
import { downloadBlob, formatBytes } from "../../media";
import type { Song, SongStage } from "../../types";
import type { TabProps } from "../SongEditor";
import { Field } from "../ui";

const stages: SongStage[] = ["種", "制作中", "推敲中", "完成", "保留"];
export function SettingsTab({ song, patchSong, notify }: TabProps & { patchSong(patch: Partial<Song>): void }) {
  const [usage, setUsage] = useState<{ usage?: number; quota?: number }>({}); const [lastBackup, setLastBackup] = useState<string>(); const [theme, setTheme] = useState<"system" | "light" | "dark">("system");
  useEffect(() => { navigator.storage?.estimate().then(setUsage); db.meta.get("lastBackupAt").then((item) => setLastBackup(item?.value as string | undefined)); db.meta.get("theme").then((item) => { const value = item?.value as typeof theme | undefined; if (value) setTheme(value); }); }, []);
  function chooseTheme(value: typeof theme) { setTheme(value); document.documentElement.dataset.theme = value === "system" ? "" : value; void db.meta.put({ key: "theme", value }); }
  async function backup() { try { const result = await createBackupBlob(); downloadBlob(result.blob, `アートメモバックアップ-${result.manifest.createdAt.slice(0, 10)}.zip`); setLastBackup(result.manifest.createdAt); notify("バックアップを書き出しました。ファイルアプリでiCloud Driveへ保存できます。"); } catch (error) { notify(error instanceof Error ? error.message : "バックアップに失敗しました。"); } }
  const backupAge = lastBackup ? (Date.now() - new Date(lastBackup).getTime()) / 86_400_000 : Infinity;
  return <section className="tab-page settings-page"><div className="tab-heading"><h2>設定</h2></div><div className="settings-card"><h3>曲について</h3><div className="detail-grid"><Field label="曲名"><input value={song.title} onChange={(e) => patchSong({ title: e.target.value })} /></Field><Field label="仮タイトル"><input value={song.workingTitle} onChange={(e) => patchSong({ workingTitle: e.target.value })} /></Field><Field label="作品の概要" wide><textarea value={song.summary} onChange={(e) => patchSong({ summary: e.target.value })} /></Field><Field label="主人公"><input value={song.protagonist} onChange={(e) => patchSong({ protagonist: e.target.value })} /></Field><Field label="相手"><input value={song.counterpart} onChange={(e) => patchSong({ counterpart: e.target.value })} /></Field><Field label="場所"><input value={song.place} onChange={(e) => patchSong({ place: e.target.value })} /></Field><Field label="時間"><input value={song.time} onChange={(e) => patchSong({ time: e.target.value })} /></Field><Field label="視点"><input value={song.perspective} onChange={(e) => patchSong({ perspective: e.target.value })} /></Field><Field label="基本色"><div className="color-field"><input type="color" value={song.baseColor} onChange={(e) => patchSong({ baseColor: e.target.value, color: e.target.value })} /><input value={song.baseColor} onChange={(e) => patchSong({ baseColor: e.target.value, color: e.target.value })} /></div></Field><Field label="繰り返す言葉"><input value={song.repeatedWords} onChange={(e) => patchSong({ repeatedWords: e.target.value })} /></Field><Field label="繰り返す物"><input value={song.repeatedObjects} onChange={(e) => patchSong({ repeatedObjects: e.target.value })} /></Field><Field label="使用を避けたい表現" wide><textarea value={song.avoidExpressions} onChange={(e) => patchSong({ avoidExpressions: e.target.value })} /></Field><Field label="聴き手に残したい感情" wide><textarea value={song.lastingEmotion} onChange={(e) => patchSong({ lastingEmotion: e.target.value })} /></Field><Field label="制作段階"><select value={song.stage} onChange={(e) => patchSong({ stage: e.target.value as SongStage })}>{stages.map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="タグ（読点区切り）"><input value={song.tags.join("、")} onChange={(e) => patchSong({ tags: e.target.value.split(/[、,]/).map((x) => x.trim()).filter(Boolean) })} /></Field></div></div>
    <div className="settings-card"><h3>バックアップ</h3>{backupAge > 14 && <p className="gentle-warning">{lastBackup ? "前回のバックアップから2週間以上経っています。" : "まだバックアップを作成していません。"}</p>}<dl><div><dt>最後のバックアップ</dt><dd>{lastBackup ? new Date(lastBackup).toLocaleString("ja-JP") : "まだありません"}</dd></div></dl><button className="primary full" onClick={backup}>すべてをZIPで書き出す</button><p className="help-text">iPhoneでは、ダウンロード後の共有メニューから「ファイルに保存」→ iCloud Driveを選べます。復元と置換はホーム画面の ⇩ から行えます。</p></div>
    <div className="settings-card"><h3>端末の保存容量</h3><div className="storage-meter"><div style={{ width: `${usage.usage && usage.quota ? Math.max(2, usage.usage / usage.quota * 100) : 0}%` }} /></div><p>{usage.usage != null ? formatBytes(usage.usage) : "計算中"} 使用中{usage.quota ? ` ／ 上限の目安 ${formatBytes(usage.quota)}` : ""}</p><small>SafariがこのWebサイト用に確保している容量の目安です。画像は長辺2048pxを上限に縮小します。</small></div>
    <div className="settings-card"><h3>表示</h3><div className="segmented">{([ ["system", "端末設定"], ["light", "ライト"], ["dark", "ダーク"] ] as const).map(([value, label]) => <button key={value} className={theme === value ? "active" : ""} onClick={() => chooseTheme(value)}>{label}</button>)}</div></div>
    <div className="privacy-card"><b>● この端末の中だけ</b><p>歌詞・画像・音声・スケッチを外部サーバーへ送る処理はありません。広告、アクセス解析、ユーザー登録、課金APIも使用していません。</p></div>
  </section>;
}
