import { useCallback, useEffect, useRef, useState } from "react";
import { db, markSongUsed, now, uid } from "../../db";
import { downloadBlob } from "../../media";
import { buildSketchPrompt, copyToClipboard, SKETCH_PROMPT_OPTIONS, type ExportBackground } from "../../settings";
import type { AspectRatio, Point, SketchAnnotationElement, SketchFill, SketchPromptFields, SketchRecord, SketchShapeElement, SketchShapeType, SketchTextElement, SketchTextSize, Stroke } from "../../types";
import type { TabProps } from "../SongEditor";
import { BlobImage } from "../ui";

type Tool = "select" | "pen" | "eraser" | "text" | "shape" | "annotation";
type Selection = { type: "text" | "shape" | "annotation"; id: string };
type CanvasSnapshot = { strokes: Stroke[]; texts: SketchTextElement[]; shapes: SketchShapeElement[]; annotations: SketchAnnotationElement[] };
type PointerInfo = { start: Point; last: Point; clientX: number; clientY: number };
type ActiveOperation = { before: CanvasSnapshot; kind: "stroke" | "shape" | "text-move" | "shape-move" | "annotation-move"; id?: string; index?: number; last?: Point };

const ratioFor = (aspect: AspectRatio) => aspect === "16:9" ? 16 / 9 : aspect === "9:16" ? 9 / 16 : 1;
const textScale = (size: SketchTextSize) => size === "small" ? .04 : size === "large" ? .085 : .06;
const clamp = (value: number, min = 0, max = 1) => Math.min(max, Math.max(min, value));
const snapshotOf = (record: SketchRecord): CanvasSnapshot => ({ strokes: structuredClone(record.strokes ?? []), texts: structuredClone(record.texts ?? []), shapes: structuredClone(record.shapes ?? []), annotations: structuredClone(record.annotations ?? []) });
const withSnapshot = (record: SketchRecord, value: CanvasSnapshot): SketchRecord => ({ ...record, ...value });
const normalizedSketch = (record: SketchRecord): SketchRecord => ({ ...record, aspect: record.aspect ?? "16:9", strokes: record.strokes ?? [], texts: record.texts ?? [], arrows: record.arrows ?? [], shapes: record.shapes ?? [], annotations: record.annotations ?? [], guideVisible: record.guideVisible ?? true, guideInExport: record.guideInExport ?? false, underlayInExport: record.underlayInExport ?? true, backgroundColor: record.backgroundColor ?? "#fffdf9", promptFields: record.promptFields ?? {}, initialName: record.initialName ?? record.name });
const isSketchMeaningful = (record: SketchRecord) => Boolean(record.strokes?.length || record.texts?.length || record.shapes?.length || record.annotations?.length || record.underlayBlob || (record.initialName && record.name.trim() !== record.initialName.trim()));

const shapeLabels: Array<[SketchShapeType, string]> = [["rectangle", "四角形"], ["ellipse", "円・楕円"], ["line", "直線"], ["triangle", "三角形"], ["person", "人物"]];

function drawArrow(ctx: CanvasRenderingContext2D, start: Point, target: Point, color: string, lineWidth: number, width: number, height: number) {
  const x1 = start.x * width; const y1 = start.y * height; const x2 = target.x * width; const y2 = target.y * height; const angle = Math.atan2(y2 - y1, x2 - x1); const head = Math.max(11, lineWidth * 4);
  ctx.save(); ctx.strokeStyle = color; ctx.fillStyle = color; ctx.lineWidth = lineWidth; ctx.lineCap = "round"; ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.beginPath(); ctx.moveTo(x2, y2); ctx.lineTo(x2 - head * Math.cos(angle - Math.PI / 6), y2 - head * Math.sin(angle - Math.PI / 6)); ctx.lineTo(x2 - head * Math.cos(angle + Math.PI / 6), y2 - head * Math.sin(angle + Math.PI / 6)); ctx.closePath(); ctx.fill(); ctx.restore();
}

function drawShape(ctx: CanvasRenderingContext2D, shape: SketchShapeElement, canvasWidth: number, canvasHeight: number, selected = false, preview = false) {
  const x = shape.position.x * canvasWidth; const y = shape.position.y * canvasHeight; const w = Math.max(2, shape.size.x * canvasWidth); const h = Math.max(2, shape.size.y * canvasHeight);
  ctx.save(); if (preview) ctx.globalAlpha = .45; ctx.translate(x + w / 2, y + h / 2); ctx.rotate(shape.rotation * Math.PI / 180); ctx.strokeStyle = shape.color; ctx.fillStyle = shape.color; ctx.lineWidth = shape.width; ctx.lineCap = "round"; ctx.lineJoin = "round";
  const fill = () => { if (shape.fill !== "none") { ctx.save(); ctx.globalAlpha *= shape.fill === "translucent" ? .25 : 1; ctx.fill(); ctx.restore(); } ctx.stroke(); };
  ctx.beginPath();
  if (shape.type === "rectangle") { ctx.rect(-w / 2, -h / 2, w, h); fill(); }
  else if (shape.type === "ellipse") { ctx.ellipse(0, 0, w / 2, h / 2, 0, 0, Math.PI * 2); fill(); }
  else if (shape.type === "line") { ctx.moveTo(-w / 2, -h / 2); ctx.lineTo(w / 2, h / 2); ctx.stroke(); }
  else if (shape.type === "triangle") { ctx.moveTo(0, -h / 2); ctx.lineTo(w / 2, h / 2); ctx.lineTo(-w / 2, h / 2); ctx.closePath(); fill(); }
  else { const head = Math.min(w, h) * .2; ctx.arc(0, -h * .3, head, 0, Math.PI * 2); ctx.stroke(); ctx.beginPath(); ctx.moveTo(0, -h * .3 + head); ctx.lineTo(0, h * .18); ctx.moveTo(-w * .28, -h * .02); ctx.lineTo(w * .28, -h * .02); ctx.moveTo(0, h * .18); ctx.lineTo(-w * .22, h * .48); ctx.moveTo(0, h * .18); ctx.lineTo(w * .22, h * .48); ctx.stroke(); }
  if (selected) { ctx.setLineDash([6, 4]); ctx.strokeStyle = "#007aff"; ctx.lineWidth = 2; ctx.strokeRect(-w / 2 - 7, -h / 2 - 7, w + 14, h + 14); }
  ctx.restore();
}

function renderSketch(ctx: CanvasRenderingContext2D, record: SketchRecord, width: number, height: number, underlay?: HTMLImageElement, options: { guide: boolean; background: ExportBackground | "current"; selection?: Selection; previewId?: string; includeUnderlay?: boolean } = { guide: false, background: "current" }) {
  ctx.clearRect(0, 0, width, height); const background = options.background === "white" ? "#fff" : record.backgroundColor ?? "#fffdf9";
  if (options.background !== "transparent") { ctx.fillStyle = background; ctx.fillRect(0, 0, width, height); }
  if (underlay && options.includeUnderlay !== false) { ctx.save(); ctx.globalAlpha = .45; const scale = Math.min(width / underlay.naturalWidth, height / underlay.naturalHeight); const w = underlay.naturalWidth * scale; const h = underlay.naturalHeight * scale; ctx.drawImage(underlay, (width - w) / 2, (height - h) / 2, w, h); ctx.restore(); }
  for (const stroke of record.strokes ?? []) { if (!stroke.points.length) continue; ctx.save(); if (stroke.tool === "eraser" && options.background === "transparent") ctx.globalCompositeOperation = "destination-out"; ctx.strokeStyle = stroke.tool === "eraser" ? background : stroke.color; ctx.lineWidth = stroke.width; ctx.lineCap = "round"; ctx.lineJoin = "round"; ctx.beginPath(); stroke.points.forEach((point, index) => index ? ctx.lineTo(point.x * width, point.y * height) : ctx.moveTo(point.x * width, point.y * height)); if (stroke.points.length === 1) ctx.lineTo(stroke.points[0].x * width + .1, stroke.points[0].y * height + .1); ctx.stroke(); ctx.restore(); }
  for (const shape of record.shapes ?? []) drawShape(ctx, shape, width, height, options.selection?.type === "shape" && options.selection.id === shape.id, options.previewId === shape.id);
  for (const arrow of record.arrows ?? []) drawArrow(ctx, arrow.start, arrow.end, arrow.color, arrow.width, width, height);
  for (const annotation of record.annotations ?? []) { drawArrow(ctx, annotation.label, annotation.target, annotation.arrowColor, annotation.arrowWidth, width, height); ctx.save(); const px = Math.max(14, width * textScale(annotation.textSize)); ctx.font = `600 ${px}px sans-serif`; ctx.fillStyle = annotation.textColor; ctx.textBaseline = "top"; ctx.fillText(annotation.text, annotation.label.x * width, annotation.label.y * height); if (options.selection?.type === "annotation" && options.selection.id === annotation.id) { ctx.strokeStyle = "#007aff"; ctx.lineWidth = 2; ctx.setLineDash([5, 4]); ctx.strokeRect(annotation.label.x * width - 5, annotation.label.y * height - 5, Math.max(55, annotation.text.length * px * .65), px + 12); for (const point of [annotation.target, annotation.label]) { ctx.beginPath(); ctx.arc(point.x * width, point.y * height, 7, 0, Math.PI * 2); ctx.fillStyle = "#007aff"; ctx.fill(); } } ctx.restore(); }
  for (const item of record.texts ?? []) { ctx.save(); const px = Math.max(14, width * textScale(item.size)); ctx.font = `600 ${px}px sans-serif`; ctx.fillStyle = item.color; ctx.textBaseline = "top"; ctx.fillText(item.text, item.position.x * width, item.position.y * height); if (options.selection?.type === "text" && options.selection.id === item.id) { ctx.strokeStyle = "#007aff"; ctx.lineWidth = 2; ctx.setLineDash([5, 4]); ctx.strokeRect(item.position.x * width - 5, item.position.y * height - 5, Math.max(50, item.text.length * px * .65), px + 12); } ctx.restore(); }
  if (options.guide) { ctx.save(); ctx.strokeStyle = "rgba(90,90,90,.58)"; ctx.lineWidth = 1; ctx.setLineDash([7, 6]); for (const x of [1 / 3, 2 / 3]) { ctx.beginPath(); ctx.moveTo(width * x, 0); ctx.lineTo(width * x, height); ctx.stroke(); } for (const y of [1 / 3, 2 / 3]) { ctx.beginPath(); ctx.moveTo(0, height * y); ctx.lineTo(width, height * y); ctx.stroke(); } ctx.restore(); }
}

async function imageFromBlob(blob?: Blob) { if (!(blob instanceof Blob) || !blob.size) return undefined; const url = URL.createObjectURL(blob); const image = new Image(); try { await new Promise<void>((resolve, reject) => { image.onload = () => resolve(); image.onerror = () => reject(new Error("画像を読み込めませんでした。")); image.src = url; }); return image; } finally { URL.revokeObjectURL(url); } }
async function makeSketchPng(record: SketchRecord, underlay: HTMLImageElement | undefined, background: ExportBackground, guide: boolean, includeUnderlay: boolean, width = 1600) { const height = Math.round(width / ratioFor(record.aspect)); const canvas = document.createElement("canvas"); canvas.width = width; canvas.height = height; const ctx = canvas.getContext("2d"); if (!ctx) throw new Error("PNGを作成できませんでした。"); renderSketch(ctx, record, width, height, underlay, { background, guide, includeUnderlay }); return await new Promise<Blob>((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("PNGを作成できませんでした。")), "image/png")); }

export function SketchTab({ song, workspace, setWorkspace, settings, notify }: TabProps) {
  const [selectedId, setSelectedId] = useState<string | undefined>(workspace.sketches[0]?.id); const selected = workspace.sketches.find((item) => item.id === selectedId) ?? workspace.sketches[0];
  useEffect(() => () => setWorkspace((data) => ({ ...data, sketches: data.sketches.filter((item) => !item.draft || isSketchMeaningful(item)) })), [setWorkspace]);
  useEffect(() => { for (const item of workspace.sketches.filter((sketch) => !sketch.draft && (!(sketch.previewBlob instanceof Blob) || !sketch.previewBlob.size))) void (async () => { try { const next = normalizedSketch(item); const image = await imageFromBlob(next.underlayBlob); const previewBlob = await makeSketchPng(next, image, "current", false, true, 480); const updated = { ...next, previewBlob }; await db.sketches.put(updated); setWorkspace((data) => ({ ...data, sketches: data.sketches.map((sketch) => sketch.id === updated.id ? updated : sketch) })); } catch { /* 編集用データは残す */ } })(); }, [setWorkspace, workspace.sketches]);
  function addSketch() { const name = `スケッチ ${workspace.sketches.filter((item) => !item.draft).length + 1}`; const sketch: SketchRecord = { id: uid(), songId: song.id, name, initialName: name, aspect: settings.sketchDefaultAspect, strokes: [], texts: [], arrows: [], shapes: [], annotations: [], guideVisible: settings.sketchGuideDefault, guideInExport: false, underlayInExport: true, backgroundColor: "#fffdf9", promptFields: {}, draft: true, createdAt: now(), updatedAt: now() }; setWorkspace((data) => ({ ...data, sketches: [...data.sketches.filter((item) => !item.draft || isSketchMeaningful(item)), sketch] })); setSelectedId(sketch.id); }
  function update(next: SketchRecord) { setWorkspace((data) => ({ ...data, sketches: data.sketches.map((item) => item.id === next.id ? next : item) })); }
  async function remove(sketch: SketchRecord) { if (!window.confirm("このスケッチを削除しますか？")) return; if (!sketch.draft) await db.sketches.delete(sketch.id); setWorkspace((data) => ({ ...data, sketches: data.sketches.filter((item) => item.id !== sketch.id) })); setSelectedId(undefined); }
  return <section className="tab-page sketch-page"><div className="tab-heading"><h1>スケッチ</h1><button className="primary compact" onClick={addSketch}>＋ 新規</button></div><div className="sketch-picker">{workspace.sketches.map((sketch) => <button className={sketch.id === selected?.id ? "active" : ""} key={sketch.id} onClick={() => setSelectedId(sketch.id)}>{sketch.previewBlob ? <BlobImage blob={sketch.previewBlob} alt="" /> : <span className="blank-sketch" />}<span>{sketch.name}</span></button>)}</div>{selected ? <CanvasEditor key={selected.id} record={selected} settings={settings} onUpdate={update} onDelete={() => void remove(selected)} notify={notify} /> : <div className="plain-empty"><p>スケッチはありません。</p><button onClick={addSketch}>スケッチを作成</button></div>}</section>;
}

function CanvasEditor({ record, settings, onUpdate, onDelete, notify }: { record: SketchRecord; settings: TabProps["settings"]; onUpdate(next: SketchRecord): void; onDelete(): void; notify(message: string): void }) {
  const [draftState, setDraftState] = useState(() => normalizedSketch(record)); const draftRef = useRef(draftState); const draft = draftState;
  const [undoStack, setUndoStack] = useState<CanvasSnapshot[]>([]); const [redoStack, setRedoStack] = useState<CanvasSnapshot[]>([]); const [tool, setTool] = useState<Tool>("pen"); const [color, setColor] = useState(settings.sketchPenColor); const [width, setWidth] = useState(settings.sketchPenWidth); const [shapeType, setShapeType] = useState<SketchShapeType>("rectangle"); const [selection, setSelection] = useState<Selection>(); const [previewId, setPreviewId] = useState<string>();
  const [textDialog, setTextDialog] = useState<Point>(); const [annotationDialog, setAnnotationDialog] = useState<{ target: Point; label: Point; before: CanvasSnapshot }>(); const [newText, setNewText] = useState(""); const [newTextSize, setNewTextSize] = useState<SketchTextSize>(settings.sketchTextSize); const [annotationMode, setAnnotationMode] = useState<"label" | "target">("label"); const [fullscreen, setFullscreen] = useState(false); const [manualPrompt, setManualPrompt] = useState(false); const [view, setView] = useState({ x: 0, y: 0, zoom: 1 });
  const canvasRef = useRef<HTMLCanvasElement>(null); const underlayImage = useRef<HTMLImageElement | undefined>(undefined); const pointers = useRef(new Map<number, PointerInfo>()); const activeOperation = useRef<ActiveOperation | undefined>(undefined); const gesture = useRef<{ active: boolean; started: number; moved: boolean; center: { x: number; y: number }; distance: number; view: typeof view }>({ active: false, started: 0, moved: false, center: { x: 0, y: 0 }, distance: 0, view }); const promptRef = useRef<HTMLTextAreaElement>(null); const ratio = ratioFor(draft.aspect);
  function updateDraft(next: SketchRecord | ((current: SketchRecord) => SketchRecord)) { const value = typeof next === "function" ? next(draftRef.current) : next; draftRef.current = value; setDraftState(value); onUpdate(value); }
  async function persist(next = draftRef.current) { let value = { ...next, updatedAt: now() }; if (!isSketchMeaningful(value) && value.draft) { updateDraft(value); return; } value = { ...value, draft: false }; const previewBlob = await makeSketchPng(value, underlayImage.current, "current", false, true, 480); value = { ...value, previewBlob }; await db.sketches.put(value); await markSongUsed(value.songId); updateDraft(value); }
  function commit(before: CanvasSnapshot) { setUndoStack((items) => [...items.slice(-39), before]); setRedoStack([]); void persist().catch(() => notify("スケッチを保存できませんでした。")); }

  const redraw = useCallback(() => { const canvas = canvasRef.current; if (!canvas) return; const rect = canvas.getBoundingClientRect(); const dpr = Math.min(window.devicePixelRatio || 1, 3); const pixelWidth = Math.max(1, Math.round(rect.width * dpr)); const pixelHeight = Math.max(1, Math.round(rect.height * dpr)); if (canvas.width !== pixelWidth || canvas.height !== pixelHeight) { canvas.width = pixelWidth; canvas.height = pixelHeight; } const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); renderSketch(ctx, draftRef.current, rect.width, rect.height, underlayImage.current, { guide: Boolean(draftRef.current.guideVisible), background: "current", selection, previewId, includeUnderlay: true }); }, [previewId, selection]);
  useEffect(() => { redraw(); }, [draft, redraw]); useEffect(() => { let cancelled = false; void imageFromBlob(draft.underlayBlob).then((image) => { if (!cancelled) { underlayImage.current = image; redraw(); } }).catch(() => notify("下敷き画像を読み込めませんでした。")); return () => { cancelled = true; }; }, [draft.underlayBlob, notify, redraw]); useEffect(() => { const observer = new ResizeObserver(redraw); if (canvasRef.current) observer.observe(canvasRef.current); return () => observer.disconnect(); }, [redraw, ratio, fullscreen]); useEffect(() => { if (!fullscreen) return; const old = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = old; }; }, [fullscreen]);
  function pointFromEvent(event: React.PointerEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return { x: clamp((event.clientX - rect.left) / rect.width), y: clamp((event.clientY - rect.top) / rect.height) }; }
  function findSelection(point: Point): Selection | undefined { const text = [...(draftRef.current.texts ?? [])].reverse().find((item) => Math.abs(point.x - item.position.x) < .17 && Math.abs(point.y - item.position.y) < .09); if (text) return { type: "text", id: text.id }; const annotation = [...(draftRef.current.annotations ?? [])].reverse().find((item) => Math.hypot(point.x - item.label.x, point.y - item.label.y) < .12 || Math.hypot(point.x - item.target.x, point.y - item.target.y) < .07); if (annotation) return { type: "annotation", id: annotation.id }; const shape = [...(draftRef.current.shapes ?? [])].reverse().find((item) => point.x >= item.position.x - .03 && point.x <= item.position.x + item.size.x + .03 && point.y >= item.position.y - .03 && point.y <= item.position.y + item.size.y + .03); return shape ? { type: "shape", id: shape.id } : undefined; }
  const pointerPair = () => [...pointers.current.values()].slice(0, 2); const centerOf = (pair: PointerInfo[]) => ({ x: (pair[0].clientX + pair[1].clientX) / 2, y: (pair[0].clientY + pair[1].clientY) / 2 }); const distanceOf = (pair: PointerInfo[]) => Math.hypot(pair[0].clientX - pair[1].clientX, pair[0].clientY - pair[1].clientY);
  function pointerDown(event: React.PointerEvent<HTMLCanvasElement>) { event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); const point = pointFromEvent(event); pointers.current.set(event.pointerId, { start: point, last: point, clientX: event.clientX, clientY: event.clientY });
    if (pointers.current.size === 2) { if (activeOperation.current) updateDraft((current) => withSnapshot(current, activeOperation.current!.before)); activeOperation.current = undefined; setPreviewId(undefined); const pair = pointerPair(); gesture.current = { active: true, started: Date.now(), moved: false, center: centerOf(pair), distance: distanceOf(pair), view }; return; }
    if (pointers.current.size > 1 || gesture.current.active) return; const before = snapshotOf(draftRef.current);
    if (tool === "pen" || tool === "eraser") { const stroke: Stroke = { tool, color, width, points: [point] }; const index = draftRef.current.strokes.length; updateDraft((current) => ({ ...current, strokes: [...current.strokes, stroke] })); activeOperation.current = { before, kind: "stroke", index }; }
    else if (tool === "shape") { const id = uid(); const shape: SketchShapeElement = { id, type: shapeType, position: point, size: { x: 0, y: 0 }, rotation: 0, color, width, fill: "none" }; updateDraft((current) => ({ ...current, shapes: [...(current.shapes ?? []), shape] })); setPreviewId(id); activeOperation.current = { before, kind: "shape", id }; }
    else if (tool === "select") { const found = findSelection(point); setSelection(found); if (found) activeOperation.current = { before, kind: found.type === "text" ? "text-move" : found.type === "shape" ? "shape-move" : "annotation-move", id: found.id, last: point }; }
  }
  function pointerMove(event: React.PointerEvent<HTMLCanvasElement>) { const point = pointFromEvent(event); const pointer = pointers.current.get(event.pointerId); if (!pointer) return; pointer.last = point; pointer.clientX = event.clientX; pointer.clientY = event.clientY;
    if (gesture.current.active && pointers.current.size >= 2) { event.preventDefault(); const pair = pointerPair(); const center = centerOf(pair); const distance = distanceOf(pair); const moved = Math.hypot(center.x - gesture.current.center.x, center.y - gesture.current.center.y); const scale = distance / Math.max(1, gesture.current.distance); if (moved > 7 || Math.abs(scale - 1) > .03) gesture.current.moved = true; setView({ x: gesture.current.view.x + center.x - gesture.current.center.x, y: gesture.current.view.y + center.y - gesture.current.center.y, zoom: clamp(gesture.current.view.zoom * scale, .75, 4) }); return; }
    if (pointers.current.size > 1) return; const operation = activeOperation.current; if (!operation) return; event.preventDefault();
    if (operation.kind === "stroke") updateDraft((current) => ({ ...current, strokes: current.strokes.map((stroke, index) => index === operation.index ? { ...stroke, points: [...stroke.points, point] } : stroke) }));
    else if (operation.kind === "shape") { const start = pointer.start; updateDraft((current) => ({ ...current, shapes: (current.shapes ?? []).map((shape) => shape.id === operation.id ? { ...shape, position: { x: Math.min(start.x, point.x), y: Math.min(start.y, point.y) }, size: { x: Math.abs(point.x - start.x), y: Math.abs(point.y - start.y) } } : shape) })); }
    else if (operation.last) { const dx = point.x - operation.last.x; const dy = point.y - operation.last.y; operation.last = point; if (operation.kind === "text-move") updateDraft((current) => ({ ...current, texts: (current.texts ?? []).map((item) => item.id === operation.id ? { ...item, position: { x: clamp(item.position.x + dx), y: clamp(item.position.y + dy) } } : item) })); else if (operation.kind === "shape-move") updateDraft((current) => ({ ...current, shapes: (current.shapes ?? []).map((item) => item.id === operation.id ? { ...item, position: { x: clamp(item.position.x + dx, 0, 1 - item.size.x), y: clamp(item.position.y + dy, 0, 1 - item.size.y) } } : item) })); else updateDraft((current) => ({ ...current, annotations: (current.annotations ?? []).map((item) => item.id === operation.id ? annotationMode === "target" ? { ...item, target: point } : { ...item, label: { x: clamp(item.label.x + dx), y: clamp(item.label.y + dy) } } : item) })); }
  }
  function pointerUp(event: React.PointerEvent<HTMLCanvasElement>) { event.preventDefault(); const pointer = pointers.current.get(event.pointerId); pointers.current.delete(event.pointerId); if (gesture.current.active) { if (!pointers.current.size) { const tap = !gesture.current.moved && Date.now() - gesture.current.started < 320; gesture.current.active = false; if (tap) undo(); } return; } const operation = activeOperation.current; activeOperation.current = undefined;
    if (operation?.kind === "shape") { const shape = draftRef.current.shapes?.find((item) => item.id === operation.id); setPreviewId(undefined); setTool("select"); const tooSmall = !shape || (shape.type === "line" ? Math.hypot(shape.size.x, shape.size.y) < .015 : shape.size.x < .015 || shape.size.y < .015); if (!shape || tooSmall) { updateDraft((current) => withSnapshot(current, operation.before)); return; } setSelection({ type: "shape", id: shape.id }); commit(operation.before); }
    else if (operation) commit(operation.before);
    else if (pointer && tool === "text" && Math.hypot(pointer.last.x - pointer.start.x, pointer.last.y - pointer.start.y) < .025) { setNewText(""); setNewTextSize(settings.sketchTextSize); setTextDialog(pointer.start); }
    else if (pointer && tool === "annotation" && Math.hypot(pointer.last.x - pointer.start.x, pointer.last.y - pointer.start.y) >= .025) { setNewText(""); setNewTextSize(settings.sketchTextSize); setAnnotationDialog({ target: pointer.start, label: pointer.last, before: snapshotOf(draftRef.current) }); }
  }
  function undo() { setUndoStack((items) => { const previous = items.at(-1); if (!previous) return items; setRedoStack((redo) => [...redo.slice(-39), snapshotOf(draftRef.current)]); const next = withSnapshot(draftRef.current, previous); updateDraft(next); void persist(next); return items.slice(0, -1); }); }
  function redo() { setRedoStack((items) => { const nextSnapshot = items.at(-1); if (!nextSnapshot) return items; setUndoStack((undo) => [...undo.slice(-39), snapshotOf(draftRef.current)]); const next = withSnapshot(draftRef.current, nextSnapshot); updateDraft(next); void persist(next); return items.slice(0, -1); }); }
  function clearAll() { if (!window.confirm("線、図形、文字、注釈をすべて消しますか？")) return; const before = snapshotOf(draftRef.current); updateDraft((current) => ({ ...current, strokes: [], texts: [], shapes: [], annotations: [], arrows: [] })); setSelection(undefined); commit(before); }
  function addText() { if (!textDialog || !newText.trim()) return; const before = snapshotOf(draftRef.current); const item: SketchTextElement = { id: uid(), text: newText.trim(), position: textDialog, color, size: newTextSize }; updateDraft((current) => ({ ...current, texts: [...(current.texts ?? []), item] })); setSelection({ type: "text", id: item.id }); setTextDialog(undefined); setTool("select"); commit(before); }
  function addAnnotation() { if (!annotationDialog || !newText.trim()) { setAnnotationDialog(undefined); setTool("select"); return; } const item: SketchAnnotationElement = { id: uid(), text: newText.trim(), target: annotationDialog.target, label: annotationDialog.label, textColor: color, textSize: newTextSize, arrowColor: color, arrowWidth: width }; updateDraft((current) => ({ ...current, annotations: [...(current.annotations ?? []), item] })); setSelection({ type: "annotation", id: item.id }); setAnnotationDialog(undefined); setTool("select"); commit(annotationDialog.before); }
  function patchElement(key: "texts" | "shapes" | "annotations", id: string, patch: Record<string, unknown>, history = true) { const before = snapshotOf(draftRef.current); const next = { ...draftRef.current, [key]: ((draftRef.current[key] ?? []) as Array<{ id: string }>).map((item) => item.id === id ? { ...item, ...patch } : item) } as SketchRecord; updateDraft(next); if (history) commit(before); else void persist(next); }
  function deleteSelected() { if (!selection) return; const before = snapshotOf(draftRef.current); const key = selection.type === "text" ? "texts" : selection.type === "shape" ? "shapes" : "annotations"; updateDraft((current) => ({ ...current, [key]: (current[key] ?? []).filter((item) => item.id !== selection.id) })); setSelection(undefined); commit(before); }
  function duplicateShape() { if (selection?.type !== "shape") return; const source = draft.shapes?.find((item) => item.id === selection.id); if (!source) return; const before = snapshotOf(draftRef.current); const copy = { ...source, id: uid(), position: { x: clamp(source.position.x + .04, 0, 1 - source.size.x), y: clamp(source.position.y + .04, 0, 1 - source.size.y) } }; updateDraft((current) => ({ ...current, shapes: [...(current.shapes ?? []), copy] })); setSelection({ type: "shape", id: copy.id }); commit(before); }
  function moveShapeLayer(front: boolean) { if (selection?.type !== "shape") return; const before = snapshotOf(draftRef.current); const list = [...(draftRef.current.shapes ?? [])]; const index = list.findIndex((item) => item.id === selection.id); if (index < 0) return; const [item] = list.splice(index, 1); if (front) list.push(item); else list.unshift(item); updateDraft((current) => ({ ...current, shapes: list })); commit(before); }
  async function setUnderlay(file?: File) { if (!file) return; const next = { ...draftRef.current, underlayBlob: file, updatedAt: now() }; updateDraft(next); try { await persist(next); } catch { notify("下敷き画像を保存できませんでした。"); } }
  function patchRecord(patch: Partial<SketchRecord>) { const next = { ...draftRef.current, ...patch, updatedAt: now() }; updateDraft(next); void persist(next).catch(() => notify("スケッチを保存できませんでした。")); }
  async function save(exportImage = false) { try { const blob = await makeSketchPng(draftRef.current, underlayImage.current, exportImage ? settings.sketchExportBackground : "current", Boolean(draftRef.current.guideInExport), exportImage ? Boolean(draftRef.current.underlayInExport) : true); const next = { ...draftRef.current, previewBlob: blob, draft: false, updatedAt: now() }; await db.sketches.put(next); await markSongUsed(next.songId); updateDraft(next); if (exportImage) { const file = new File([blob], `${next.name || "スケッチ"}.png`, { type: "image/png" }); const nav = navigator as Navigator & { canShare?: (data: ShareData) => boolean }; if (navigator.share && nav.canShare?.({ files: [file] })) { try { await navigator.share({ files: [file], title: next.name }); } catch (error) { if (!(error instanceof DOMException && error.name === "AbortError")) downloadBlob(blob, file.name); } } else downloadBlob(blob, file.name); } notify(exportImage ? "スケッチ画像を用意しました。" : "スケッチを保存しました。"); } catch (error) { notify(error instanceof Error ? error.message : "スケッチを保存できませんでした。"); } }
  async function copyPrompt() { const prompt = buildSketchPrompt(draft.promptFields); if (await copyToClipboard(prompt)) { notify("画像生成用の命令文をコピーしました"); return; } setManualPrompt(true); requestAnimationFrame(() => { promptRef.current?.focus(); promptRef.current?.select(); }); }
  const selectedText = selection?.type === "text" ? draft.texts?.find((item) => item.id === selection.id) : undefined; const selectedShape = selection?.type === "shape" ? draft.shapes?.find((item) => item.id === selection.id) : undefined; const selectedAnnotation = selection?.type === "annotation" ? draft.annotations?.find((item) => item.id === selection.id) : undefined;

  return <article className={`canvas-editor ${fullscreen ? "fullscreen" : ""}`}><div className="sketch-name-row"><input value={draft.name} onChange={(event) => patchRecord({ name: event.target.value })} aria-label="スケッチ名" /><div className="canvas-icon-toolbar"><button onClick={() => setFullscreen((value) => !value)}>{fullscreen ? "全画面終了" : "全画面編集"}</button><button onClick={undo} disabled={!undoStack.length} aria-label="一つ戻す">↶</button><button onClick={redo} disabled={!redoStack.length} aria-label="やり直す">↷</button><button onClick={clearAll} aria-label="全消去">全消去</button></div></div>
    <div className="canvas-tools" aria-label="描画ツール"><button className={tool === "select" ? "active" : ""} onClick={() => setTool("select")}><span>選択</span></button><button className={tool === "pen" ? "active" : ""} onClick={() => setTool("pen")}><span>ペン</span></button><button className={tool === "eraser" ? "active" : ""} onClick={() => setTool("eraser")}><span>消去</span></button><button className={tool === "shape" ? "active" : ""} onClick={() => setTool("shape")}><span>図形</span></button><button className={tool === "text" ? "active" : ""} onClick={() => setTool("text")}><span>文字</span></button><button className={tool === "annotation" ? "active" : ""} onClick={() => setTool("annotation")}><span>注釈</span></button></div>
    {tool === "shape" && <div className="shape-picker">{shapeLabels.map(([id, label]) => <button key={id} className={shapeType === id ? "active" : ""} onClick={() => setShapeType(id)}>{label}</button>)}</div>}
    <div className="drawing-options"><label><span>色</span><input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label><label><span>太さ</span><input type="range" min="1" max="28" value={width} onChange={(event) => setWidth(Number(event.target.value))} /></label><label><span>背景</span><input type="color" value={draft.backgroundColor} onChange={(event) => patchRecord({ backgroundColor: event.target.value })} /></label></div>
    <div className="aspect-row"><div className="segmented small">{(["16:9", "9:16", "1:1"] as AspectRatio[]).map((aspect) => <button key={aspect} className={draft.aspect === aspect ? "active" : ""} onClick={() => patchRecord({ aspect })}>{aspect}</button>)}</div><label className="small-file"><input type="file" accept="image/*" onChange={(event) => void setUnderlay(event.target.files?.[0])} />{draft.underlayBlob ? "下敷きを変更" : "画像を下敷き"}</label></div>
    <div className="guide-row"><label className="switch-row"><span>三分割ガイド</span><input type="checkbox" checked={Boolean(draft.guideVisible)} onChange={(event) => patchRecord({ guideVisible: event.target.checked })} /></label><label className="switch-row"><span>ガイドをPNGに含める</span><input type="checkbox" checked={Boolean(draft.guideInExport)} onChange={(event) => patchRecord({ guideInExport: event.target.checked })} /></label>{draft.underlayBlob && <label className="switch-row"><span>下敷きをPNGに含める</span><input type="checkbox" checked={Boolean(draft.underlayInExport)} onChange={(event) => patchRecord({ underlayInExport: event.target.checked })} /></label>}</div>
    <div className="canvas-viewport"><div className="canvas-stage" style={{ aspectRatio: ratio, transform: `translate(${view.x}px, ${view.y}px) scale(${view.zoom})` }}><canvas ref={canvasRef} aria-label="スケッチキャンバス" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} /></div></div><button className="reset-view" onClick={() => setView({ x: 0, y: 0, zoom: 1 })}>表示位置を戻す</button>
    {selectedText && <div className="element-editor"><strong>文字</strong><input value={selectedText.text} onChange={(event) => patchElement("texts", selectedText.id, { text: event.target.value }, false)} /><select value={selectedText.size} onChange={(event) => patchElement("texts", selectedText.id, { size: event.target.value as SketchTextSize })}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select><input type="color" value={selectedText.color} onChange={(event) => patchElement("texts", selectedText.id, { color: event.target.value })} /><button className="danger-text" onClick={deleteSelected}>削除</button></div>}
    {selectedShape && <div className="element-editor shape-editor"><strong>{shapeLabels.find(([id]) => id === selectedShape.type)?.[1]}</strong><label>幅<input type="range" min=".02" max="1" step=".01" value={selectedShape.size.x} onChange={(event) => patchElement("shapes", selectedShape.id, { size: { ...selectedShape.size, x: Number(event.target.value) } }, false)} /></label><label>高さ<input type="range" min=".02" max="1" step=".01" value={selectedShape.size.y} onChange={(event) => patchElement("shapes", selectedShape.id, { size: { ...selectedShape.size, y: Number(event.target.value) } }, false)} /></label><label>回転<input type="range" min="-180" max="180" value={selectedShape.rotation} onChange={(event) => patchElement("shapes", selectedShape.id, { rotation: Number(event.target.value) }, false)} /></label><input type="color" value={selectedShape.color} onChange={(event) => patchElement("shapes", selectedShape.id, { color: event.target.value })} /><input type="range" min="1" max="28" value={selectedShape.width} onChange={(event) => patchElement("shapes", selectedShape.id, { width: Number(event.target.value) }, false)} /><select value={selectedShape.fill} onChange={(event) => patchElement("shapes", selectedShape.id, { fill: event.target.value as SketchFill })}><option value="none">塗りなし</option><option value="translucent">半透明</option><option value="solid">不透明</option></select><button onClick={duplicateShape}>複製</button><button onClick={() => moveShapeLayer(true)}>前面へ</button><button onClick={() => moveShapeLayer(false)}>背面へ</button><button className="danger-text" onClick={deleteSelected}>削除</button></div>}
    {selectedAnnotation && <div className="element-editor annotation-editor"><strong>注釈</strong><input value={selectedAnnotation.text} onChange={(event) => patchElement("annotations", selectedAnnotation.id, { text: event.target.value }, false)} /><div className="segmented small"><button className={annotationMode === "label" ? "active" : ""} onClick={() => setAnnotationMode("label")}>説明文を移動</button><button className={annotationMode === "target" ? "active" : ""} onClick={() => setAnnotationMode("target")}>指す位置を変更</button></div><select value={selectedAnnotation.textSize} onChange={(event) => patchElement("annotations", selectedAnnotation.id, { textSize: event.target.value as SketchTextSize })}><option value="small">文字 小</option><option value="medium">文字 中</option><option value="large">文字 大</option></select><label>文字色<input type="color" value={selectedAnnotation.textColor} onChange={(event) => patchElement("annotations", selectedAnnotation.id, { textColor: event.target.value })} /></label><label>矢印色<input type="color" value={selectedAnnotation.arrowColor} onChange={(event) => patchElement("annotations", selectedAnnotation.id, { arrowColor: event.target.value })} /></label><input type="range" min="1" max="28" value={selectedAnnotation.arrowWidth} onChange={(event) => patchElement("annotations", selectedAnnotation.id, { arrowWidth: Number(event.target.value) }, false)} /><button className="danger-text" onClick={deleteSelected}>削除</button></div>}
    {!fullscreen && <><details className="sketch-prompt-fields"><summary>画像の条件</summary><div>{SKETCH_PROMPT_OPTIONS.map((item) => <label key={item.key}><span>{item.label}</span><textarea rows={2} value={draft.promptFields?.[item.key] ?? ""} onChange={(event) => patchRecord({ promptFields: { ...(draftRef.current.promptFields ?? {}), [item.key]: event.target.value } as SketchPromptFields })} /></label>)}</div></details><div className="canvas-actions"><button className="primary" onClick={() => void save(true)}>画像として保存</button><button onClick={() => void copyPrompt()}>画像生成用の命令文をコピー</button></div>{manualPrompt && <label className="prompt-preview"><span>手動でコピー</span><textarea ref={promptRef} readOnly rows={9} value={buildSketchPrompt(draft.promptFields)} /></label>}<button className="danger-text sketch-delete" onClick={onDelete}>このスケッチを削除</button></>}
    {textDialog && <EntryDialog title="文字を追加" text={newText} setText={setNewText} size={newTextSize} setSize={setNewTextSize} color={color} setColor={setColor} onClose={() => { setTextDialog(undefined); setTool("select"); }} onAdd={addText} />}{annotationDialog && <EntryDialog title="注釈を追加" text={newText} setText={setNewText} size={newTextSize} setSize={setNewTextSize} color={color} setColor={setColor} onClose={() => { setAnnotationDialog(undefined); setTool("select"); }} onAdd={addAnnotation} />}
  </article>;
}

function EntryDialog({ title, text, setText, size, setSize, color, setColor, onClose, onAdd }: { title: string; text: string; setText(value: string): void; size: SketchTextSize; setSize(value: SketchTextSize): void; color: string; setColor(value: string): void; onClose(): void; onAdd(): void }) { return <div className="modal-backdrop text-entry-backdrop"><div className="modal text-entry"><div className="modal-title"><h2>{title}</h2><button aria-label="閉じる" onClick={onClose}>×</button></div><input autoFocus value={text} onChange={(event) => setText(event.target.value)} /><label>サイズ<select value={size} onChange={(event) => setSize(event.target.value as SketchTextSize)}><option value="small">小</option><option value="medium">中</option><option value="large">大</option></select></label><label className="setting-color">色<input type="color" value={color} onChange={(event) => setColor(event.target.value)} /></label><button className="primary full" disabled={!text.trim()} onClick={onAdd}>追加</button></div></div>; }
